In [ ]:
!pip install transformers

In [ ]:
import torch

In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
import random

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
random_seed=42

In [ ]:
random.seed(random_seed)

In [ ]:
torch.manual_seed(random_seed)

In [ ]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [ ]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
model=BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [ ]:
text="ineuron is for the best AI Courses."

In [ ]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [ ]:
input_ids=encoding["input_ids"]

In [ ]:
input_ids

tensor([[  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
          1012,   102]])

In [ ]:
attention_mask=encoding["attention_mask"]

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [ ]:
word_embeddings.shape

torch.Size([1, 12, 768])

In [ ]:
word_embeddings

tensor([[[-0.4271, -0.1666,  0.1909,  ..., -0.2987,  0.6356,  0.6963],
         [-0.4555, -0.5843,  0.3312,  ..., -0.1475,  0.5605,  1.2290],
         [-0.7174, -0.4126,  1.0531,  ...,  0.3063,  0.3983,  0.2660],
         ...,
         [ 0.3224,  0.1035,  0.5626,  ..., -0.2507, -0.0866, -0.3084],
         [ 0.5164,  0.1578, -0.0727,  ...,  0.2103, -0.4651, -0.2494],
         [ 0.2963,  0.2963,  0.2604,  ...,  0.3185, -0.6820, -0.1199]]])

In [ ]:
input_ids[0]

tensor([  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
         1012,   102])

In [ ]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [ ]:
decode

'ineuron is for the best ai courses.'